In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
# Sentences 

sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
# Define the vocabulary size
voc_size=10000

# One hot representation - following is the meaning for the code below

# for each word in sent --> convert to one_hot representation by one_hot[words,voc_size] - which means 
# convert each word in sent to one_hot representation of size specified in voc_size 
# all of this should be in a list


onehot_repr=[one_hot(words,voc_size)for words in sent]
print(onehot_repr)

[[9902, 5350, 5840, 6554], [9902, 5350, 5840, 8043], [9902, 4732, 5840, 8332], [4048, 8773, 9416, 9630, 1858], [4048, 8773, 9416, 9630, 8267], [2276, 9902, 1715, 5840, 1579], [1251, 4981, 3037, 9630]]


In [4]:
# Word Embedding Representation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences # using to make the length of all the sentences same
from tensorflow.keras.models import Sequential
import numpy as np

In [5]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 9902 5350 5840 6554]
 [   0    0    0    0 9902 5350 5840 8043]
 [   0    0    0    0 9902 4732 5840 8332]
 [   0    0    0 4048 8773 9416 9630 1858]
 [   0    0    0 4048 8773 9416 9630 8267]
 [   0    0    0 2276 9902 1715 5840 1579]
 [   0    0    0    0 1251 4981 3037 9630]]


In [6]:
# Feature representation

dim = 10

In [7]:
# Building the model
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [8]:
# Predicting the model

model.predict(embedded_docs)

1/1 [==============================] - 0s 492ms/step


array([[[ 0.02358968,  0.04412072,  0.0077306 ,  0.044503  ,
         -0.00331629,  0.024351  , -0.02552297,  0.02169957,
         -0.02305473,  0.04704437],
        [ 0.02358968,  0.04412072,  0.0077306 ,  0.044503  ,
         -0.00331629,  0.024351  , -0.02552297,  0.02169957,
         -0.02305473,  0.04704437],
        [ 0.02358968,  0.04412072,  0.0077306 ,  0.044503  ,
         -0.00331629,  0.024351  , -0.02552297,  0.02169957,
         -0.02305473,  0.04704437],
        [ 0.02358968,  0.04412072,  0.0077306 ,  0.044503  ,
         -0.00331629,  0.024351  , -0.02552297,  0.02169957,
         -0.02305473,  0.04704437],
        [ 0.01253817, -0.04399419,  0.0291397 , -0.04573432,
         -0.01948807, -0.01880038,  0.02475926, -0.00579072,
          0.03193973,  0.02325222],
        [ 0.0137823 , -0.04019479, -0.01363289, -0.0123873 ,
         -0.01071467,  0.03664747,  0.02558837,  0.04502255,
         -0.047094  ,  0.00855412],
        [ 0.03632868, -0.01359668,  0.04179518,  0.0

In [9]:
embedded_docs[0]

array([   0,    0,    0,    0, 9902, 5350, 5840, 6554])

In [10]:
model.predict(embedded_docs)[0]

1/1 [==============================] - 0s 90ms/step


array([[ 0.02358968,  0.04412072,  0.0077306 ,  0.044503  , -0.00331629,
         0.024351  , -0.02552297,  0.02169957, -0.02305473,  0.04704437],
       [ 0.02358968,  0.04412072,  0.0077306 ,  0.044503  , -0.00331629,
         0.024351  , -0.02552297,  0.02169957, -0.02305473,  0.04704437],
       [ 0.02358968,  0.04412072,  0.0077306 ,  0.044503  , -0.00331629,
         0.024351  , -0.02552297,  0.02169957, -0.02305473,  0.04704437],
       [ 0.02358968,  0.04412072,  0.0077306 ,  0.044503  , -0.00331629,
         0.024351  , -0.02552297,  0.02169957, -0.02305473,  0.04704437],
       [ 0.01253817, -0.04399419,  0.0291397 , -0.04573432, -0.01948807,
        -0.01880038,  0.02475926, -0.00579072,  0.03193973,  0.02325222],
       [ 0.0137823 , -0.04019479, -0.01363289, -0.0123873 , -0.01071467,
         0.03664747,  0.02558837,  0.04502255, -0.047094  ,  0.00855412],
       [ 0.03632868, -0.01359668,  0.04179518,  0.03860435, -0.02776756,
         0.0019212 ,  0.00332869, -0.02240319